### ISSUE TITLE
Error after upgrading to 2021.8.0

### ISSUE THREAD

**Issue by joaovitoriasilva** [dgomes/ha_erse#11]
2021-08-04 12:26:33 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform erse

```
Traceback (most recent call last):


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities


    await asyncio.gather(*tasks)


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity


    await entity.add_to_platform_finish()


  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish


    await self.async_added_to_hass()


  File "/config/custom_components/erse/sensor.py", line 202, in async_added_to_hass


    self._update_cost()


  File "/config/custom_components/erse/sensor.py", line 184, in _update_cost


    energy_state.attributes[ATTR_LAST_RESET]


AttributeError: 'NoneType' object has no attribute 'attributes'


2021-08-04 12:26:33 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up erse platform for sensor


Traceback (most recent call last):


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform


    await asyncio.gather(*pending)


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities


    await asyncio.gather(*tasks)


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity


    await entity.add_to_platform_finish()


  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish


    await self.async_added_to_hass()


  File "/config/custom_components/erse/sensor.py", line 202, in async_added_to_hass


    self._update_cost()


  File "/config/custom_components/erse/sensor.py", line 184, in _update_cost


    energy_state.attributes[ATTR_LAST_RESET]


AttributeError: 'NoneType' object has no attribute 'attributes'
```

**Comment by dgomes** [comment]
Por favor actualizar o ERSE

**Comment by joaovitoriasilva** [comment]
Boa noite,

Atualizado para v1.1.1. Agora com outro erro:
2021-08-04 22:35:02 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up erse platform for sensor


Traceback (most recent call last):


  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform


    await asyncio.shield(task)


  File "/config/custom_components/erse/sensor.py", line 61, in async_setup_entry


    for tariff, cost in config_entry.data[CONF_COST].items():


KeyError: 'cost'

**Comment by joaovitoriasilva** [comment]
Nota: no manifest.json da v.1.1.1 continua a dizer que a versão é a 1.0.3

**Comment by dgomes** [comment]
Apagou a configuração antiga e fez uma nova ?

**Comment by joaovitoriasilva** [comment]
Boas. Voltei a realizar essa operação e após dois reboots ao container do HA ficou OK. Obrigado
